#!/bin/bash
sudo apt install openssl -y
sudo apt install tree -y
#mkdir subca
#cd subca
#cp /home/pratham/subca.cnf /home/pratham/subca/
mkdir -p csr certs crl newcerts private
chmod 777 private
touch index.txt
touch index.txt.attr
echo '1000'>serial
echo '1000'>crlnumber
openssl genrsa -aes256 -out private/subca.key.pem 4096
chmod 400 private/subca.key.pem
openssl req -config subca.cnf -new -sha256 -key private/subca.key.pem -out csr/subca.csr.pem
scp csr/subca.csr.pem pratham@192.168.80.10:/home/pratham/ca/subca/csr
echo 'go to rootca for signing'
